1.	1.	По заболеваемости COVID 19 – из csse_covid_19_data\csse_covid_19_daily_reports объединяем ежедневные данные только за 2021 год в один датасет

In [19]:
import pandas as pd    
from pathlib import Path
import os

In [20]:
# вставить свой индивидуальный абсолютный PATH:

In [21]:
ABSOLUTE_DIRECTORY_PATH = 'C:\\Users\\aanal\\PycharmProjects\\Final_Project_Geekbrains\\Start_datasets_COVID\\'

In [22]:
PREPARED_DATASET_COVID_PATH = 'joined_dataset_COVID.csv'
Start_datasets_COVID_PATH = ".\Start_datasets_COVID\csse_covid_19_daily_reports"
Start_datasets_COVID_PATH_US = ".\Start_datasets_COVID\csse_covid_19_daily_reports_us"

In [23]:
# i_need = 'C:\\Users\\aanal\\PycharmProjects\\Final_Project_Geekbrains\\Start_datasets_COVID\\csse_covid_19_daily_reports\\'
# p = ABSOLUTE_DIRECTORY_PATH + Start_datasets_COVID_PATH.replace('.\\','').replace('Start_datasets_COVID\\','') + '\\'
# print(p)
# i_need == p
# p = Start_datasets_COVID_PATH.replace('.\\','\\')
# p

In [24]:
# os.listdir(Start_datasets_COVID_PATH)

In [25]:
# path = Start_datasets_COVID_PATH
# condition = '2021'
# for root, dirs, files in os.walk(path):  
#         for filename in files:
#             if condition in filename and '.csv' in filename:
#                 p = ABSOLUTE_DIRECTORY_PATH + path.replace('.\\','') +'\\'+  filename
#                 print(p)

Объединяем в один дата фрейм файлы из csse_covid_19_daily_reports

In [26]:
def join_several_to_one (absolute_path, path, result_file_name, condition):  
    #делаем список имен файлов для единого датасета с исключением ненужных лет в названии
    abs_list = []
    for root, dirs, files in os.walk(path):  
        for filename in files:
            if condition in filename and '.csv' in filename:
#                 p = absolute_path + path.replace('.\\','') +'\\'+  filename
                p = absolute_path + path.replace('.\\','').replace('Start_datasets_COVID\\','') + '\\' + filename
#                 print(p)             
                abs_list.append(p)
            else:
    #             print('Нашел 2022', filename)
                continue
   
    print(len(abs_list))
    
    #делаем единый датасет
    frame = pd.DataFrame()
    list_ = []
    for file_ in abs_list:
        df = pd.read_csv(file_,index_col=None, header=0)
        list_.append(df)
    frame = pd.concat(list_)
    
    #Видим, что поле дата все равно папопали даты содержащие 2022 год убираем их, оставляя в поле только 2021 год
    frame = frame[frame['Last_Update'].apply(lambda x: condition in x)]
    
    frame.to_csv(result_file_name, index=False)
    
    return frame

In [27]:
condition = '2021'
df_1 = join_several_to_one (ABSOLUTE_DIRECTORY_PATH, Start_datasets_COVID_PATH, str(PREPARED_DATASET_COVID_PATH.replace('.csv','') + '_1' + '.csv'), condition)
df_1

365

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-01-02 05:22:33,33.939110,67.709953,52513,2201,41727.0,8585.0,Afghanistan,134.896578,4.191343
1,NaN,NaN,NaN,Albania,2021-01-02 05:22:33,41.153300,20.168300,58316,1181,33634.0,23501.0,Albania,2026.409062,2.025173
2,NaN,NaN,NaN,Algeria,2021-01-02 05:22:33,28.033900,1.659600,99897,2762,67395.0,29740.0,Algeria,227.809861,2.764848
3,NaN,NaN,NaN,Andorra,2021-01-02 05:22:33,42.506300,1.521800,8117,84,7463.0,570.0,Andorra,10505.403482,1.034865
4,NaN,NaN,NaN,Angola,2021-01-02 05:22:33,-11.202700,17.873900,17568,405,11146.0,6017.0,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,NaN,NaN,Unknown,Spain,2021-04-25 23:20:49,NaN,NaN,0,0,NaN,NaN,"Unknown, Spain",NaN,NaN
2270,29147.0,Nodaway,Missouri,US,2021-12-19 23:20:51,40.360798,-94.881330,4141,37,NaN,NaN,"Nodaway, Missouri, US",18744.341843,0.893504
2479,90032.0,Unassigned,Nevada,US,2021-01-24 23:22:19,NaN,NaN,0,0,NaN,NaN,"Unassigned, Nevada, US",NaN,NaN
3097,72888.0,Out of PR,Puerto Rico,US,2021-10-10 23:21:42,NaN,NaN,434,0,NaN,NaN,"Out of PR, Puerto Rico, US",NaN,0.000000
3847,90054.0,Unassigned,West Virginia,US,2021-07-31 23:21:38,NaN,NaN,0,0,NaN,NaN,"Unassigned, West Virginia, US",NaN,NaN

In [28]:
cols_1 = df_1.columns
cols_1

Index(['FIPS', 'Admin2', 'Province_State', 'Country_Region', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key', 'Incident_Rate', 'Case_Fatality_Ratio'],
      dtype='object')

In [29]:

# list_2021 = []
# abs_list_2021 = []
# for root, dirs, files in os.walk(Start_datasets_COVID_PATH):  
#     for filename in files:
#         if '2021' in filename and '.csv' in filename:
# #             print(filename)
# #             p = os.path.abspath(filename)
#             p = 'C:\\Users\\aanal\\PycharmProjects\\Final_Project_Geekbrains\\Start_datasets_COVID\\csse_covid_19_daily_reports\\' + filename
#             print(p)
#             list_2021.append(filename)
#             abs_list_2021.append(p)
#         else:
# #             print('Нашел 2022', filename)
#             continue
# # print(list_2021)
# print(len(list_2021))
# # print(list_2021)
# print(len(abs_list_2021))

In [30]:
# # path =r'C:\DRO\DCL_rawdata_files' # use your path
# # allFiles = glob.glob(path + "/*.csv")
# frame = pd.DataFrame()
# list_ = []
# for file_ in abs_list_2021:
# #     file_path = str(Start_datasets_COVID_PATH + '\\' + file_)
# #     print('file_path', file_path)
#     df = pd.read_csv(file_,index_col=None, header=0)
#     list_.append(df)
# frame = pd.concat(list_)
# frame.to_csv(PREPARED_DATASET_COVID_PATH, index=False)

Объединяем в один дата фрейм файлы из csse_covid_19_daily_reports_us

In [31]:
# list_2021_us = []
# abs_list_2021_us = []
# for root, dirs, files in os.walk(Start_datasets_COVID_PATH):  
#     for filename in files:
#         if '2021' in filename and '.csv' in filename:
# #             print(filename)
# #             p = os.path.abspath(filename)
#             p = 'C:\\Users\\aanal\\PycharmProjects\\Final_Project_Geekbrains\\Start_datasets_COVID\\csse_covid_19_daily_reports\\' + filename
#             print(p)
#             list_2021.append(filename)
#             abs_list_2021.append(p)
#         else:
# #             print('Нашел 2022', filename)
#             continue
# # print(list_2021)
# print(len(list_2021))
# # print(list_2021)
# print(len(abs_list_2021))

In [32]:
condition = '2021'
df_2 = join_several_to_one (ABSOLUTE_DIRECTORY_PATH, Start_datasets_COVID_PATH_US, str(PREPARED_DATASET_COVID_PATH.replace('.csv','') + '_2' + '.csv'), condition)
df_2

365

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,2021-01-02 05:30:44,32.3182,-86.9023,365747,4872,202137.0,158738.0,1.0,7459.375895,3275341.0,NaN,1.332068,84000001.0,USA,66800.273700,NaN
1,Alaska,US,2021-01-02 05:30:44,61.3707,-152.4044,47019,206,7165.0,39648.0,2.0,6427.355802,1275750.0,NaN,0.438121,84000002.0,USA,174391.185778,NaN
2,American Samoa,US,2021-01-02 05:30:44,-14.2710,-170.1320,0,0,NaN,NaN,60.0,0.000000,2140.0,NaN,NaN,16.0,ASM,3846.084722,NaN
3,Arizona,US,2021-01-02 05:30:44,33.7298,-111.4312,530267,9015,76934.0,444318.0,4.0,7285.171274,5155330.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN
4,Arkansas,US,2021-01-02 05:30:44,34.9697,-92.3731,229442,3711,199247.0,26484.0,5.0,7602.945718,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Virginia,US,2021-12-31 04:33:06,37.7693,-78.1700,1100900,15565,NaN,NaN,51.0,12897.868308,11132438.0,NaN,1.413843,84000051.0,USA,130424.851728,NaN
54,Washington,US,2021-12-31 04:33:06,47.4009,-121.4905,849075,9853,NaN,NaN,53.0,11150.189504,9958651.0,NaN,1.160439,84000053.0,USA,130778.607132,NaN
55,West Virginia,US,2021-12-31 04:33:06,38.4912,-80.9545,328162,5336,NaN,NaN,54.0,18311.109524,4919310.0,NaN,1.626026,84000054.0,USA,274492.549997,NaN
56,Wisconsin,US,2021-12-31 04:33:06,44.2685,-89.6165,1112655,11151,NaN,NaN,55.0,19109.791541,13255586.0,NaN,1.002197,84000055.0,USA,227663.997565,NaN
57,Wyoming,US,2021-12-31 04:33:06,42.7560,-107.3025,115638,1526,NaN,NaN,56.0,19980.337239,1199877.0,NaN,1.319635,84000056.0,USA,207318.935861,NaN

In [33]:
cols_2 = df_2.columns
cols_2

Index(['Province_State', 'Country_Region', 'Last_Update', 'Lat', 'Long_',
       'Confirmed', 'Deaths', 'Recovered', 'Active', 'FIPS', 'Incident_Rate',
       'Total_Test_Results', 'People_Hospitalized', 'Case_Fatality_Ratio',
       'UID', 'ISO3', 'Testing_Rate', 'Hospitalization_Rate'],
      dtype='object')

In [34]:
list3=list(set(cols_1)-set(cols_2))  
print (list3 )

['Combined_Key', 'Admin2']

In [35]:
set(cols_2)

{'Active',
 'Case_Fatality_Ratio',
 'Confirmed',
 'Country_Region',
 'Deaths',
 'FIPS',
 'Hospitalization_Rate',
 'ISO3',
 'Incident_Rate',
 'Last_Update',
 'Lat',
 'Long_',
 'People_Hospitalized',
 'Province_State',
 'Recovered',
 'Testing_Rate',
 'Total_Test_Results',
 'UID'}

In [36]:
set(cols_1)

{'Active',
 'Admin2',
 'Case_Fatality_Ratio',
 'Combined_Key',
 'Confirmed',
 'Country_Region',
 'Deaths',
 'FIPS',
 'Incident_Rate',
 'Last_Update',
 'Lat',
 'Long_',
 'Province_State',
 'Recovered'}

# Вывод

Видим, что в двух полученных датасетах сильно отличаются столбцы (структура данных). Также видим, что в датасете номер 2 
с данными по US мы имеем данные по отдельным штатам, а не по городам. Сравнивать это с данными по загрязнению, 
которые представлены по отдельным городам не имеет смысла.
Решение - используем только ДАТАСЕТ 1 - 'joined_dataset_COVID_1.csv'